datalake:
  outputs:

    dev:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [dev_username]
      pass: [dev_password]
      dbname: [dbname]
      schema: [dev_schema]

    prod:
      type: postgres
      threads: 1
      host: datalake
      port: 5432
      user: datalake
      pass: datalake
      dbname: datalake
      schema: staging

  target: prod
