apiVersion: v1
kind: Service
metadata:
  name: api-flask-service
spec:
  type: ClusterIP 
  selector:
    app: api-flask  # O valor de "app" deve corresponder ao label usado nos Pods da sua aplicação
  ports:
    - port: 5000       # Porta que o serviço vai escutar dentro do cluster
      targetPort: 5000  # Porta que a sua API Flask estará escutando dentro do container
  